win32-installer:
        script:
                - C:\Python27\Scripts\pyinstaller.exe -F ZopeEdit.spec
        artifacts:
                paths:
                        - build\ZopeEdit\zopeedit.exe
