install:
        - choco install -y innosetup
        - pip install pyinstaller==3.3

build_script:
        - pyinstaller.exe -D ZopeEdit.spec
        - '"C:\Program Files (x86)\Inno Setup 5\Compil32.exe" /cc collective\zopeedit\win32\setup.iss'
artifacts:
  - path: collective\zopeedit\win32\Output\*
    name: installer
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'collective.zopeedit: installer for Windows'
  provider: GitHub
  auth_token:
    secure: ZpHA71SYuWiMOd6z8dVWy5PXckXUyCOenoaNnx8xLEGBJ/LOEJuIbBE7AJJH8cBf
  artifact: installer
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: false        # deploy on tag push only
