install:
        - choco install -y innosetup
        - pip install pyinstaller==3.3

build_script:
        - pyinstaller.exe ZopeEdit.spec
        - '"C:\Program Files (x86)\Inno Setup 5\Compil32.exe" /cc collective\zopeedit\win32\setup.iss'
artifacts:
  - path: collective\zopeedit\win32\Output\*
    name: installer
deploy:
  release: collective.zopeedit-v$(appveyor_repo_tag)
  description: 'collective.zopeedit Windows installer'
  provider: GitHub
  auth_token:
    secure: ZpHA71SYuWiMOd6z8dVWy5PXckXUyCOenoaNnx8xLEGBJ/LOEJuIbBE7AJJH8cBf
  artifact: installer
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
