install:
        - choco install -y innosetup
        - pip install pyinstaller==3.3
        - pip install pytest

build_script:
        - pyinstaller.exe -D ZopeEdit.spec
        - '"C:\Program Files (x86)\Inno Setup 5\Compil32.exe" /cc collective\zopeedit\win32\setup.iss'
test_script:
        - collective\zopeedit\win32\Output\zopeedit-win32-1.1.0.exe /VERYSILENT
        - python -m pytest tests
artifacts:
  - path: collective\zopeedit\win32\Output\*
    name: installer
deploy:
  release: '$(APPVEYOR_REPO_TAG_NAME) - built by appveyor'
  description: 'collective.zopeedit: installer for Windows'
  provider: GitHub
  auth_token:
    secure: 'Dnv6xHpkOgs6VqVY+iSq5VKyr8V4oUwGTPvUXUdyRR1Ksg66O8Yx6rb2yiG6t14l'
  artifact: installer
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: false        # deploy on tag push only
