install:
        - choco install -y innosetup
        - pip install pyinstaller==3.3
        - docker version
        - python tests\bootstrap.py -c tests\buildout.cfg
        - tests\bin\buildout -Nv -c tests\buildout.cfg
        - tests\bin\instance install
        - tests\bin\instance run tests\add_file.py

services:
  - Zope1068480214

build_script:
        - pyinstaller.exe -D ZopeEdit.spec
        - '"C:\Program Files (x86)\Inno Setup 5\Compil32.exe" /cc collective\zopeedit\win32\setup.iss'
test_script:
        - collective\zopeedit\win32\Output\zopeedit-win32-1.1.0.exe /VERYSILENT
        - tests\bin\pytest tests
artifacts:
  - path: collective\zopeedit\win32\Output\*
    name: installer
deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_BRANCH)-$(APPVEYOR_REPO_COMMIT)
    description: 'collective.zopeedit: installer for Windows'
    auth_token:
      secure: 'Dnv6xHpkOgs6VqVY+iSq5VKyr8V4oUwGTPvUXUdyRR1Ksg66O8Yx6rb2yiG6t14l'
    artifact: installer
    draft: true
    prerelease: true
    on:
      appveyor_repo_tag: false        # deploy on any push
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'collective.zopeedit: installer for Windows'
    auth_token:
      secure: 'Dnv6xHpkOgs6VqVY+iSq5VKyr8V4oUwGTPvUXUdyRR1Ksg66O8Yx6rb2yiG6t14l'
    artifact: installer
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true        # deploy on tag push only
cache:
  - tests\eggs
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
